In [5]:
# checking which environment it ran on
import sys
print(sys.executable)

/home/aviraljoshi/mini-logistic-regression/.venv/bin/python3


In [6]:
# importing numpy as np
import numpy as np
print(np.__version__)

2.5.3


In [7]:
heights_cm = np.array([170, 155, 182])
print(heights_cm)
print(type(heights_cm))

[170 155 182]
<class 'numpy.ndarray'>


In [8]:
print(heights_cm.shape)
print(type(heights_cm.shape))

(3,)
<class 'tuple'>


In [9]:
print(heights_cm.ndim)
print(heights_cm.dtype)

1
int64


In [10]:
weights_kg = np.array([65.5, 50.0, 80.2])
print(weights_kg.ndim)
print(weights_kg.dtype)

1
float64


In [13]:
# Indexing and slicing a 1D array
print(heights_cm[0])
print(heights_cm[-1])
print(heights_cm[0:2])

# slicing also returns a ndarray
print(type(heights_cm[0:2]))

170
182
[170 155]
<class 'numpy.ndarray'>


In [14]:
# Loops vs vectorization
numbers = list(range(1_000_000))
numbers_array = np.array(numbers)

%timeit [n * 2 for n in numbers]
%timeit numbers_array * 2

37.5 ms ± 2.68 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
848 μs ± 75.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [16]:
#Vectors and matrices (the concept)
X = np.array([
    [14.1, 20.3, 92.0],
    [11.4, 15.7, 73.2],
    [19.8, 22.1, 130.5],
    [12.5, 18.9, 80.1],
])

print(X)
print(X.shape)
print(X.ndim)
print(X.dtype)

[[ 14.1  20.3  92. ]
 [ 11.4  15.7  73.2]
 [ 19.8  22.1 130.5]
 [ 12.5  18.9  80.1]]
(4, 3)
2
float64


In [25]:
# Indexing a matrix (rows, columns, single values)

print(X[0])
print(X[:, 0])
print(X[2, 2])


print(X[0].shape, X[:, 0].shape)

[14.1 20.3 92. ]
[14.1 11.4 19.8 12.5]
130.5
[[14.1]
 [11.4]]
[20.3 15.7]
(3,) (4,) (2, 1)


In [26]:
print(X[:2, :1])
print(X[:2, 1])

print(X[:2, :1].shape, X[:2, 1].shape)

[[14.1]
 [11.4]]
[20.3 15.7]
(2, 1) (2,)


In [28]:
# Broadcasting (the concept)

marks = np.array([
    [10, 20, 30],
    [40, 50, 60],
])
bonus = np.array([1, 2, 3])

print(marks.shape, bonus.shape)
print(marks - bonus)
print((marks - bonus).shape)

(2, 3) (3,)
[[ 9 18 27]
 [39 48 57]]
(2, 3)


### 📐 NumPy Broadcasting Rules Reference

Broadcasting allows arithmetic operations on arrays of different shapes. For an operation to work, the dimensions of the two arrays must be compatible. Starting from the trailing (rightmost) dimensions, axes are compatible if they are **equal**, or if **one of them is 1**.

| Shape A | Shape B | Rows Comparison | Columns Comparison | Status & Behavior |
| :--- | :--- | :--- | :--- | :--- |
| `(2, 3)` | `(2, 3)` | Equal ✓ | Equal ✓ | **Works** (Standard element-by-element operation) |
| `(2, 3)` | `(1, 3)` | 1 → Stretch ✓ | Equal ✓ | **Works** (Shape B stretches rows to match A) |
| `(2, 3)` | `(2, 1)` | Equal ✓ | 1 → Stretch ✓ | **Works** (Shape B stretches columns to match A) |
| `(2, 3)` | `(1, 1)` | 1 → Stretch ✓ | 1 → Stretch ✓ | **Works** (Acts like adding a single scalar) |
| `(2, 3)` | `(2, 2)` | Equal ✓ | 3 vs 2 ✗ | ❌ **Error** (Dimension mismatch; cannot stretch) |

---

### 💡 Core Takeaways

* **The Rule of 1:** A dimension of size `1` acts like a rubber band. NumPy will automatically stretch/copy it to match the larger shape along that axis without using extra memory.
* **The Mismatch Rule:** If two dimensions are different and neither is `1` (like `3` vs `2` in the final row), broadcasting fails, throwing a `ValueError`.
* **Direction of Alignment:** Always align shapes starting from the **right side** (columns first, then rows). If one array has fewer dimensions, NumPy prepends `1`s to its shape.
### 📐 NumPy Broadcasting Rules Reference

Broadcasting allows arithmetic operations on arrays of different shapes. For an operation to work, the dimensions of the two arrays must be compatible. Starting from the trailing (rightmost) dimensions, axes are compatible if they are **equal**, or if **one of them is 1**.

| Shape A | Shape B | Rows Comparison | Columns Comparison | Status & Behavior |
| :--- | :--- | :--- | :--- | :--- |
| `(2, 3)` | `(2, 3)` | Equal ✓ | Equal ✓ | **Works** (Standard element-by-element operation) |
| `(2, 3)` | `(1, 3)` | 1 → Stretch ✓ | Equal ✓ | **Works** (Shape B stretches rows to match A) |
| `(2, 3)` | `(2, 1)` | Equal ✓ | 1 → Stretch ✓ | **Works** (Shape B stretches columns to match A) |
| `(2, 3)` | `(1, 1)` | 1 → Stretch ✓ | 1 → Stretch ✓ | **Works** (Acts like adding a single scalar) |
| `(2, 3)` | `(2, 2)` | Equal ✓ | 3 vs 2 ✗ | ❌ **Error** (Dimension mismatch; cannot stretch) |

---

### 💡 Core Takeaways

* **The Rule of 1:** A dimension of size `1` acts like a rubber band. NumPy will automatically stretch/copy it to match the larger shape along that axis without using extra memory.
* **The Mismatch Rule:** If two dimensions are different and neither is `1` (like `3` vs `2` in the final row), broadcasting fails, throwing a `ValueError`.
* **Direction of Alignment:** Always align shapes starting from the **right side** (columns first, then rows). If one array has fewer dimensions, NumPy prepends `1`s to its shape.
